name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Build
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        # Inject API key directly into src/js/game.js instead of using separate config.js
        if [ ! -z "$YOUTUBE_API_KEY" ]; then
          # Add the API key as a global variable at the top of src/js/game.js
          sed -i "1i\\window.YOUTUBE_API_KEY = '$YOUTUBE_API_KEY';" src/js/game.js
          # Also replace the placeholder in the getVideoResources function
          sed -i "s/window\.YOUTUBE_API_KEY || 'YOUR_API_KEY_HERE'/window.YOUTUBE_API_KEY || '$YOUTUBE_API_KEY'/g" src/js/game.js
          echo "✅ API key injected directly into src/js/game.js"
          echo "Global API key set and function updated"
        else
          echo "⚠️ No API key found - using default placeholder"
        fi
        
        # Also create src/js/config.js as backup
        if [ ! -z "$YOUTUBE_API_KEY" ]; then
          echo "window.YOUTUBE_API_KEY = '$YOUTUBE_API_KEY';" > src/js/config.js
        else
          echo "console.log('Running in demo mode - YouTube API not configured');" > src/js/config.js
        fi
        
        # Show what we've done
        echo "First few lines of src/js/game.js:"
        head -5 src/js/game.js
        echo "API key line in getVideoResources:"
        grep -n "YOUTUBE_API_KEY.*YOUR_API_KEY_HERE\|YOUTUBE_API_KEY.*AIza" src/js/game.js || echo "API key successfully injected"
        echo "Files in root directory:"
        ls -la
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false
